### ISSUE TITLE
Error with sample_del.py

### ISSUE THREAD

**Issue by lsantuari** [mchowdh200/samplot-ml#3]
When I run:
```
bcftools view -i 'SVTYPE="DEL"' $VCF \
    | bcftools query -f '%CHROM\t%POS\t%INFO/END[\t%SAMPLE,%GT]\n' \ 
    | python sample_del.py > $OUT/del.sample.bed # from git repo
```
on the VCF file "_ALL.wgs.integrated_sv_map_v1_GRCh38.20130502.svs.genotypes.vcf.gz_" I get the following error:

```
Traceback (most recent call last):
  File "sample_del.py", line 52, in <module>
    GT=line[6]))
  File "sample_del.py", line 12, in __init__
    self.AB = float(AB) if AB != '.' else AB
ValueError: could not convert string to float: 'HG00097,0|0'
```

**Comment by brentp** [comment]
bump. this is shown in the README and there's also an error about dhffc which doesn't exist in the file shown in the README.

**Comment by mchowdh200** [comment]
I'm closing this issue due to its age.  Since this issue, I made a lot of changes to the samplot-ml workflow.  Everything is now handled with a snakemake pipeline that ensures all steps are run correctly and with the required versions of software/libraries.  In my opinion, things should be way simpler to run and you don't have to worry about what version of tensorflow, bcftools, etc. you're running with.
